// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.T_ShirtCannon.subsystems;

import org.usfirst.frc1891.T_ShirtCannon.RobotMap;
import org.usfirst.frc1891.T_ShirtCannon.commands.*;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon rightMaster = RobotMap.driveTrainRightMaster;
    private final CANTalon leftMaster = RobotMap.driveTrainLeftMaster;
    private final CANTalon leftSlave = RobotMap.driveTrainLeftSlave;
    private final CANTalon rightSlave = RobotMap.driveTrainRightSlave;
    private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    	this.setDefaultCommand(new Drive());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    /**
     * @param leftValue
     * @param rightValue
     */
    public void Drive(double leftValue, double rightValue) {
    	leftMaster.set(leftValue);
    	rightMaster.set(rightValue);
    	leftSlave.set(leftValue);
    	rightSlave.set(rightValue);
    }
}
