// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.T_ShirtCannon;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainRightMaster;
    public static CANTalon driveTrainLeftMaster;
    public static CANTalon driveTrainLeftSlave;
    public static CANTalon driveTrainRightSlave;
    public static RobotDrive driveTrainRobotDrive41;
    
    public static int topLeftBarrelPort = 1;
    public static int bottomLeftBarrelPort = 0;
    public static int topRightBarrelPort = 2;
    public static int bottomRightBarrelPort = 3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightMaster = new CANTalon(2);
        driveTrainRightMaster.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        driveTrainRightMaster.setInverted(false);
        driveTrainRightMaster.enableBrakeMode(true);
        LiveWindow.addActuator("DriveTrain", "RightMaster", driveTrainRightMaster);
        
        driveTrainLeftMaster = new CANTalon(0);
        driveTrainLeftMaster.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        driveTrainLeftMaster.setInverted(true);
        driveTrainLeftMaster.enableBrakeMode(true);
        LiveWindow.addActuator("DriveTrain", "LeftMastetr", driveTrainLeftMaster);
        
        driveTrainLeftSlave = new CANTalon(1);
        driveTrainLeftSlave.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        driveTrainLeftSlave.setInverted(true);
        driveTrainLeftSlave.enableBrakeMode(true);
        LiveWindow.addActuator("DriveTrain", "LeftSlave", driveTrainLeftSlave);
        
        driveTrainRightSlave = new CANTalon(3);
        driveTrainRightSlave.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        driveTrainRightSlave.setInverted(false);
        driveTrainRightSlave.enableBrakeMode(true);
        LiveWindow.addActuator("DriveTrain", "RightSlave", driveTrainRightSlave);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftMaster, driveTrainLeftSlave,
              driveTrainRightMaster, driveTrainRightSlave);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
